# Generated by Django 5.0.7 on 2024-09-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0003_remove_product_image_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_on_sale",
            field=models.BooleanField(default=False),
        ),
    ]
