# Generated by Django 5.0.7 on 2024-09-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0005_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
