# Generated by Django 5.0.7 on 2024-09-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0007_alter_product_discount_percentage_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment_text",
            field=models.TextField(blank=True),
        ),
    ]
