# Generated by Django 5.0.7 on 2024-10-23 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0009_product_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="page_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="comment",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment",
                to="tienda.product",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="rating",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
