# Generated by Django 5.0.7 on 2025-04-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0012_alter_orderitem_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.URLField(),
        ),
    ]
